name: Dacapo Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test-assertions:
    runs-on: ubuntu-22.04
    steps:
      # Checkout repos and submodules
      - uses: actions/checkout@v2
      - name: Setup Environments
        run: |
            ./.github/scripts/ci-checkout.sh
            ./.github/scripts/ci-setup.sh

      # Run the tests
      - name: Dacapo Tests
        run: ./.github/scripts/ci-test-assertions.sh
